# Generated by Django 3.2.16 on 2024-01-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240115_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='Lizard',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
