# Generated by Django 3.2.16 on 2024-01-19 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_lizard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='body',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Ensure the body only contains letters, numbers, spaces, commas, periods, and exclamation/question marks.', regex='^[A-Za-z0-9\\s\\.,!?]*$')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='size',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Ensure this value is greater than or equal to 1.'), django.core.validators.MaxValueValidator(100, message='Ensure this value is less than or equal to 100.')]),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Ensure the body only contains letters, numbers, spaces, commas, periods, and exclamation/question marks.', regex='^[A-Za-z0-9\\s\\.,!?]*$')]),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='diet_list',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Ensure the body only contains letters, numbers, spaces, commas, periods, and exclamation/question marks.', regex='^[A-Za-z0-9\\s\\.,!?]*$')]),
        ),
    ]
