# Generated by Django 3.2.16 on 2024-01-19 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240119_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='body',
            field=models.TextField(default='Here can be your experience...', help_text='Share your experience in 800 Characters', max_length=800),
        ),
        migrations.AlterField(
            model_name='experience',
            name='pet_name',
            field=models.CharField(default="What's your pet name?", help_text='Format: Letters only and max 80 characters', max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_letters_only', message='Only letters are allowed.', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Ensure this value is greater than or equal to 1.'), django.core.validators.MaxValueValidator(100, message='Ensure this value is less than or equal to 100.')]),
        ),
    ]
