# Generated by Django 3.2.16 on 2024-01-24 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20240119_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='likes',
        ),
        migrations.AddField(
            model_name='lizard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='lizard_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
