# Generated by Django 5.0.1 on 2024-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240124_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lizard',
            name='diet',
            field=models.IntegerField(choices=[('0', 'Not defined'), ('1', 'Omnivorous'), ('2', 'Herbivorous'), ('3', 'Insectivorous')], default=0),
        ),
    ]
