# Generated by Django 5.0.1 on 2024-02-05 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_experience_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='size',
            field=models.IntegerField(default=1, help_text='Min 1, max 100', validators=[django.core.validators.MinValueValidator(1, message='value is greater than or = to 1.'), django.core.validators.MaxValueValidator(100, message='value is less than or = to 100.')]),
        ),
    ]
